name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  NODE_VERSION: 18

jobs:
  lint:
    name: Lint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('yarn.lock') }}
            yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Lint JS & Handlebars
        run: yarn lint

  test:
    name: Tests
    needs: [lint]
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('yarn.lock') }}
            yarn-

      - name: Install dependencies (no lockfile)
        run: yarn install --no-lockfile

      - name: Run tests (floating dependencies)
        run: yarn test:ember

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ember

  try-one:
    name: Additional Tests
    needs: [test]
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        scenario:
          - ember-lts-3.24
          - ember-release

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('yarn.lock') }}
            yarn-

      - name: Install dependencies
        run: yarn install

      - uses: actions/cache@v3
        with:
          path: |
            yarn
            package
            yarn.lock
          key: yarn-${{ matrix.scenario }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('config/ember-try.js') }}
          restore-keys: |
            yarn-${{ matrix.scenario }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('config/ember-try.js') }}
            yarn-${{ matrix.scenario }}-
            yarn-

      - name: Run tests
        run: yarn ember try:one ${{ matrix.scenario }}
